# gears

appId   : "a13842d9"
domain  : ""

# SSH credentials

host     : ""
port     : "22"
username : ""
password : ""

# repository

repository :
  url      : "https://github.com/anticoders/nebula.git"
  username : ""
  password : ""

# environment settings

environment :
# you can add meteor settings here
#  METEOR_SETTINGS :
#    public:
#      hello: world
  MONGO_URL       : ""
  ROOT_URL        : "http://"

