# gears

appName : "nebula"
domain  : "nebula.com"

# repository

repository :
  url      : "https://github.com/anticoders/nebula.git"
  username : ""
  password : ""

# environment settings

environment :
# you can add meteor settings here
  METEOR_SETTINGS :
    public:
      hello: world
  MONGO_URL       : ""
  ROOT_URL        : "http://nebula.com"

# deployment configuration

deployment:

  username  : nebula
  password  : secret

  build : local

  targets:

    - host : 192.168.0.2
    - host : 192.168.0.3
    - host : 192.168.0.4
    - host : 192.168.0.5
