# gears

appId  : "{{appId}}"

# SSH credentials

host     : "{{host}}"
port     : "{{port}}"
username : "{{username}}"
password : "{{password}}"

# repository

repository :
  url : "{{repository.url}}"

# environment settings

environment :
# you can add meteor settings here
#  METEOR_SETTINGS :
#    public:
#      hello: world
  MONGO_URL       : "{{environment.MONGO_URL}}"
  ROOT_URL        : "{{environment.ROOT_URL}}"
