# gears

appId  : "1de975f6"
deploy : "staging"

# SSH credentials

host     : "192.168.33.10"
port     : "22"
username : "nebula"
password : "secret"

# repository

repository :
  url : "https://github.com/anticoders/nebula.git"

# environment settings

environment :
# you can setup meteor settings here
#  METEOR_SETTINGS :
#    public:
#      hello: world
  MONGO_URL       : ""
  ROOT_URL        : "http://192.168.33.10"

